source 'https://github.com/CocoaPods/Specs.git'


target 'ObjCBSON', :exclusive => true do
  # Temporary. See podspec.
  pod 'libbson', :git => 'https://github.com/paulmelnikow/libbson', :branch => 'podspec-1'

  pod "ObjCBSON", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag =>
'v0.3.0.beta1'
  pod 'Expecta'
end
